version: "3"
services:

  # ----------------- #
  #     PostgreSQL    #
  # ----------------- #
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

  # ----------------- #
  # ClickHouse Server #
  # ----------------- #

  clickhouse-server:
    container_name: clickhouse-server
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./dbfiles:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

  # ----------------- #
  # ClickHouse Client #
  # ----------------- #

  clickhouse-client:
    container_name: clickhouse-client
    image: clickhouse/clickhouse-client:latest
    entrypoint:
      - /bin/sleep
    command:
      - infinity

volumes:
  postgres-db:
    driver: local